_wandb:
    value:
        cli_version: 0.24.2
        e:
            dw7shta1rlhzgxdrpkxw5a33kbxp0nsh:
                args:
                    - --dataset
                    - Clothing
                    - --gpu_id
                    - "0"
                    - --seed
                    - "1572205414"
                    - --epoch
                    - "250"
                    - --verbose
                    - "5"
                    - --batch_size
                    - "1024"
                    - --lr
                    - "0.0001"
                    - --regs
                    - "0.001"
                    - --embed_size
                    - "64"
                    - --topk
                    - "5"
                    - --core
                    - "5"
                    - --User_layers
                    - "3"
                    - --Item_layers
                    - "2"
                    - --user_loss_ratio
                    - "0.03"
                    - --item_loss_ratio
                    - "0.07"
                    - --temperature
                    - "0.6"
                    - --early_stopping_patience
                    - "30"
                    - --early_stopping_min_epochs
                    - "75"
                    - --early_stopping_min_delta
                    - "0.0001"
                    - --early_stopping_monitor
                    - val_recall@20
                    - --early_stopping_mode
                    - max
                    - --early_stopping_restore_best
                    - "1"
                    - --adaptive_patience
                    - "0"
                    - --use_reduce_lr
                    - "1"
                    - --reduce_lr_factor
                    - "0.5"
                    - --reduce_lr_patience
                    - "3"
                    - --reduce_lr_min
                    - "1e-06"
                    - --use_wandb
                    - "1"
                    - --wandb_project
                    - local-mmhcl-clothing
                    - --wandb_entity
                    - baitapck51cc-uet
                    - --wandb_run_name
                    - seed_1572205414
                codePath: codes\main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "3999878082560"
                        used: "411246333952"
                email: baitapck51cc@gmail.com
                executable: c:\ProgramData\anaconda3\envs\rtx5090_dl\python.exe
                git:
                    commit: 0ceaa26ae637a65c2043a01899fbed5608428b0b
                    remote: https://github.com/Xu107/MMHCL.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-f3a7c6c6-3acf-c9eb-6d0f-29173e7f78fe
                host: DESKTOP-D28E6IO
                memory:
                    total: "134807592960"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Anh Khoi\Desktop\MyCode\My research progress\Local_MMHCL_randoms\codes\main.py
                python: CPython 3.12.12
                root: c:\Users\Anh Khoi\Desktop\MyCode\My research progress\Local_MMHCL_randoms\codes
                startedAt: "2026-02-10T13:36:48.074629Z"
                writerId: dw7shta1rlhzgxdrpkxw5a33kbxp0nsh
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.12
            "5": 0.24.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.2
            "13": windows-amd64
Item_layers:
    value: 2
Ks:
    value: '[10,20]'
UI_layers:
    value: 2
User_layers:
    value: 3
ablation_target:
    value: ""
adaptive_patience:
    value: 0
batch_size:
    value: 1024
cf_model:
    value: LightGCN
core:
    value: 5
data_path:
    value: ../data/
dataset:
    value: Clothing
debug:
    value: "True"
early_stopping_min_delta:
    value: 0.0001
early_stopping_min_epochs:
    value: 75
early_stopping_mode:
    value: max
early_stopping_monitor:
    value: val_recall@20
early_stopping_patience:
    value: 30
early_stopping_restore_best:
    value: 1
embed_size:
    value: 64
epoch:
    value: 250
gpu_id:
    value: 0
item_loss_ratio:
    value: 0.07
lr:
    value: 0.0001
norm_type:
    value: sym
path_name:
    value: uu_ii=3_2_0.03_0.07_topk=5_t=0.6_regs=0.001_dim=64_seed=1572205414_
reduce_lr_factor:
    value: 0.5
reduce_lr_min:
    value: 1e-06
reduce_lr_patience:
    value: 3
regs:
    value: 0.001
seed:
    value: 1572205414
sparse:
    value: 0
temperature:
    value: 0.6
test_flag:
    value: part
topk:
    value: 5
train_dir:
    value: train
use_reduce_lr:
    value: 1
use_wandb:
    value: 1
user_loss_ratio:
    value: 0.03
verbose:
    value: 5
wandb_entity:
    value: baitapck51cc-uet
wandb_project:
    value: local-mmhcl-clothing
wandb_run_name:
    value: seed_1572205414
weight_size:
    value: '[64,64,64]'
