_wandb:
    value:
        cli_version: 0.24.2
        e:
            nmqtac88r8i4890nt7zvvdpq53jchq8j:
                args:
                    - --dataset
                    - Clothing
                    - --gpu_id
                    - "0"
                    - --seed
                    - "304525586"
                    - --epoch
                    - "250"
                    - --verbose
                    - "5"
                    - --batch_size
                    - "1024"
                    - --lr
                    - "0.0001"
                    - --regs
                    - "0.001"
                    - --clip_grad_norm
                    - "1.0"
                    - --embed_size
                    - "64"
                    - --topk
                    - "5"
                    - --core
                    - "5"
                    - --User_layers
                    - "3"
                    - --Item_layers
                    - "2"
                    - --user_loss_ratio
                    - "0.03"
                    - --item_loss_ratio
                    - "0.07"
                    - --temperature
                    - "0.1"
                    - --early_stopping_patience
                    - "30"
                    - --early_stopping_min_epochs
                    - "75"
                    - --early_stopping_min_delta
                    - "0.0001"
                    - --early_stopping_mode
                    - max
                    - --early_stopping_restore_best
                    - "1"
                    - --use_reduce_lr
                    - "1"
                    - --reduce_lr_factor
                    - "0.5"
                    - --reduce_lr_patience
                    - "3"
                    - --reduce_lr_min
                    - "1e-06"
                    - --damps_apc
                    - "1"
                    - --damps_avrf
                    - "1"
                    - --damps_imcf
                    - "1"
                    - --damps_permutation_fft
                    - "0"
                    - --damps_soft_routing
                    - "1"
                    - --damps_momentum
                    - "1"
                    - --damps_data_driven_prior
                    - "1"
                    - --damps_num_categories
                    - "10"
                    - --damps_warmup_epochs
                    - "10"
                    - --rebuild_R
                    - "5"
                    - --faiss_threshold
                    - "60000"
                    - --faiss_use_gpu
                    - "1"
                    - --knn_chunk_size
                    - "4096"
                    - --knn_efsearch
                    - "64"
                    - --use_amp
                    - "1"
                    - --use_torch_compile
                    - "1"
                    - --torch_compile_mode
                    - reduce-overhead
                    - --torch_compile_dynamic
                    - "1"
                    - --use_wandb
                    - "1"
                    - --wandb_project
                    - damps-mmhcl-clothing
                    - --wandb_entity
                    - baitapck51cc-uet
                    - --wandb_run_name
                    - seed_304525586
                codePath: MMHCL_DAMPS_Project\train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "3999878082560"
                        used: "1254728085504"
                email: baitapck51cc@gmail.com
                executable: c:\ProgramData\anaconda3\envs\rtx5090_dl\python.exe
                git:
                    commit: b3e6d416663ea44ca1d487636dd818ef66305753
                    remote: https://github.com/sunflower82/DAMPS_upgrade_for_MMHCL_randoms_Amazon_Clothing.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-f3a7c6c6-3acf-c9eb-6d0f-29173e7f78fe
                host: DESKTOP-D28E6IO
                memory:
                    total: "134807584768"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Anh Khoi\Desktop\MyCode\My research progress\DAMPS_upgrade_for_MMHCL_randoms_Amazon_Clothing\MMHCL_DAMPS_Project\train.py
                python: CPython 3.12.12
                root: c:\Users\Anh Khoi\Desktop\MyCode\My research progress\DAMPS_upgrade_for_MMHCL_randoms_Amazon_Clothing\MMHCL_DAMPS_Project
                startedAt: "2026-04-30T13:33:28.249745Z"
                writerId: nmqtac88r8i4890nt7zvvdpq53jchq8j
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.2
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.2
            "13": windows-amd64
Item_layers:
    value: 2
Ks:
    value: '[10,20]'
UI_layers:
    value: 2
User_layers:
    value: 3
ablation_target:
    value: ""
batch_size:
    value: 1024
cf_model:
    value: LightGCN
clip_grad_norm:
    value: 1
core:
    value: 5
damps_apc:
    value: 1
damps_avrf:
    value: 1
damps_data_driven_prior:
    value: 1
damps_imcf:
    value: 1
damps_momentum:
    value: 1
damps_num_categories:
    value: 10
damps_permutation_fft:
    value: 0
damps_soft_routing:
    value: 1
damps_warmup_epochs:
    value: 10
data_path:
    value: ../data/
dataset:
    value: Clothing
debug:
    value: "True"
early_stopping_min_delta:
    value: 0.0001
early_stopping_min_epochs:
    value: 75
early_stopping_mode:
    value: max
early_stopping_patience:
    value: 30
early_stopping_restore_best:
    value: 1
embed_size:
    value: 64
epoch:
    value: 250
faiss_threshold:
    value: 60000
faiss_use_gpu:
    value: 1
gpu_id:
    value: 0
item_loss_ratio:
    value: 0.07
knn_chunk_size:
    value: 4096
knn_efsearch:
    value: 64
lr:
    value: 0.0001
norm_type:
    value: sym
path_name:
    value: damps_uu_ii=3_2_0.03_0.07_topk=5_t=0.1_R=5_apc=1_avrf=1_imcf=1_regs=0.001_dim=64_seed=304525586_
rebuild_R:
    value: 5
reduce_lr_factor:
    value: 0.5
reduce_lr_min:
    value: 1e-06
reduce_lr_patience:
    value: 3
regs:
    value: 0.001
seed:
    value: 304525586
sparse:
    value: 0
temperature:
    value: 0.1
test_flag:
    value: part
topk:
    value: 5
torch_compile_dynamic:
    value: 1
torch_compile_mode:
    value: reduce-overhead
use_amp:
    value: 1
use_reduce_lr:
    value: 1
use_torch_compile:
    value: 1
use_wandb:
    value: 1
user_loss_ratio:
    value: 0.03
verbose:
    value: 5
wandb_entity:
    value: baitapck51cc-uet
wandb_project:
    value: damps-mmhcl-clothing
wandb_run_name:
    value: seed_304525586
weight_size:
    value: '[64,64,64]'
